export default function Head() {
  return (
    <>
      <title>Carlos Hurtatiz | Frontend web developer</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="/assets/images/logoSimbolo.svg" 
        type="image/svg+xml"
      />
    </>
  )
}
